### ISSUE TITLE
event_store service in the latest 1.0.x-dev event-store-symfony-bundle

### ISSUE THREAD

**Issue by vilnitsky** [prooph/event-store-symfony-bundle#16]
Could someone please advice if it is possible to use the dev version of event-store-symfony-bundle already?

I can't figure out how to create PostgresEventStore with transactions to use in event_store as before.

Since event-store-doctrine-adapter is deprecated, it isn't possible to create event store using DoctrineEventStoreAdapter I suppose we should use pdo-event-store somehow now.

**Comment by sandrokeil** [comment]
@vilnitsky Look at this [diff](https://github.com/inowas/inowas_api/commit/c0dff18c17c283331010f5fa0e776496f30e1392) for migrating to Event Store V7 with own factories. It's not hard to use your own factories.

**Comment by vilnitsky** [comment]
@sandrokeil thanks, I also figured out that there is a PR waiting https://github.com/prooph/event-store-symfony-bundle/pull/10
We should be good once it is merged.
