### ISSUE TITLE
Read model projections not deleted and reset

### ISSUE THREAD

**Issue by camuthig** [prooph/event-store-symfony-bundle#18]
Using the latest projection configurations and commands, when a `ReadModel` is set on a projection and either `event-store:projection:delete` or `event-store:projection:reset` is called the `delete` and `reset` functions on the `ReadModel` are not also called.

**Comment by webdevilopers** [comment]
I read the referenced issues for this @camuthig . Maybe I am misunderstanding the functionality of these commands. As @codeliner states:

> The projection manager only tells the projection to delete/reset by adding a corresponding status command in the projection table.
* https://github.com/prooph/event-store-symfony-bundle/pull/19#issuecomment-333329608

What I expected calling "reset" would is executing the "reset" method on my "read model class" e.g. from the proophessor example:

```php
final class TodoReadModel extends AbstractReadModel
{
    public function reset(): void
    {
        $tableName = Table::TODO;
        $sql = "TRUNCATE TABLE '$tableName';";
        $statement = $this->connection->prepare($sql);
        $statement->execute();
    }
```

* https://github.com/prooph/proophessor-do-symfony/blob/master/src/ProophessorDo/Projection/Todo/TodoReadModel.php#L71-L79

This is not the case and seems to be the expected behaviour. But where to run / use these methods instead?

**Comment by camuthig** [comment]
@webdevilopers I believe I made the same assumption you did when I originally wrote the ticket. The `reset` command does not directly call the function on your read model. All the reset command does is set the state of your read model. If you look at the implementation in the [MySqlProjectionManager](https://github.com/prooph/pdo-event-store/blob/master/src/Projection/MySqlProjectionManager.php#L172-L181), for example, you will see that the projection manager's function is just calling a basic `UPDATE` on a row in the projection's table.

The second part of executing a reset is that you need your projection to be actively running to notice that change, and call call the function on your read model. So for calling delete/reset/stop on your projection usually requires two terminals: one that is running your projection and another where you call the command to delete/reset/stop your project. 

I hope that helps.

**Comment by webdevilopers** [comment]
Thanks for the feedback.
Did I get this right? I open two terminals. One running:
```
/usr/bin/php /var/www/foo/bin/console event-store:projection:run bar
``` 
And keep it running.

Then in a second terminal I can call:
```
/usr/bin/php /var/www/foo/bin/console event-store:projection:delete bar
```

Then the read model "delete" method is supposed to be called?
Because that is not happening in my case. Instead the first command stops running. And the table was not dropped. Also not resetted / truncated.

Or are we talking about a different command for `reset` and `delete` on the read model?
Because I see no other offered by the symfony bridge. Maybe we are talking about custom console commands I should write myself?

**Comment by webdevilopers** [comment]
Any feedback would be appreciated.

For instance is calling "event-store:projection:delete" supposed to execte the `delete` method on the Read Model? Or does e.g an SQL table ALTER require manually deleting the old table and start running the projection again?

```php
final class FooReadModel extends AbstractReadModel
{
    public function delete(): void
    {
        $tableName = Table::FOO;

        $sql = "DROP TABLE `$tableName`;";

        $statement = $this->connection->prepare($sql);
        $statement->execute();
    }
}
```

**Comment by camuthig** [comment]
@webdevilopers it has been a long time for me, so I'll do my best to explain this as far as I can recollect.

Calling the `event-store:projection:delete` command does not call the `delete` method on the read model. It calls the `ProjectionManager` `deleteProjection` method. If you are, for example, using the Postgres event store, then this will execute an update on the projections table, setting the status of the projection as something like `deleting`.

https://github.com/prooph/pdo-event-store/blob/v1.12.0/src/Projection/PostgresProjectionManager.php#L136

This is why the read model projection must be running in a second terminal to do anything. The running projection will see that the status of the projection itself has changed and call the read model's delete method.

https://github.com/prooph/pdo-event-store/blob/f26bcf042176d396354526770c720624feba7005/src/Projection/PdoEventStoreReadModelProjector.php#L453

**Comment by webdevilopers** [comment]
Thanks @camuthig for clearing this up. What was the original intent in version 7 of adding the method on the read model then?

* https://github.com/prooph/event-store/blob/7.x/src/Projection/ReadModel.php#L24

**Comment by camuthig** [comment]
I didn't implement this logic, so take my input with a grain of salt.

As you already noted, the method on the read model is meant to remove data from the model. For example, in the [proophessor-do example](https://github.com/prooph/proophessor-do/blob/master/src/Projection/Todo/TodoReadModel.php#L86) it drops all of the data from the SQL table.

The interfaces may have been implemented this way to allow for separating the concerns of deleting a projection (allowing you to stop creating new data to a read model), from deleting the data of the read model.

For example, you might create a read model based on data you have in your event stream up to now, but not want to continue running the projection going forward, so you delete the projection and retain the read model.

I believe this is the case because the `ReadModelProjector`'s [delete](https://github.com/prooph/event-store/blob/7.x/src/Projection/ReadModelProjector.php#L82) accepts a `$deleteProjection` parameter, that if true, calls the `delete` function on the `ReadModel` after deleting the projection.
