### ISSUE TITLE
Bump event store package

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store-symfony-bundle#2]
- [ ] bump version to event-store v7
- [ ] identify required changes in the set up logic
    - event store interface
    - new plugin registration
    - Aggregate and Snapshot namespaces moved to prooph/event-sourcing
    - persistent projections
- [ ] tbd

**Comment by codeliner** [comment]
@rabbl @mablae @UFOMelkor I've added some notes. Let me know if you need more details!

**Comment by rabbl** [comment]
As symfony ships with doctrine by default, we could provide a doctrine-eventstore instead of the pdoEventstore. Or inject the doctrine connection to the pdoEventStore.

**Comment by prolic** [comment]
You can inject the connection, but doctrine dbal is not good for event
store, because it lacks batch inserts.

Am 22.02.2017 14:24 schrieb "Ralf Junghanns" <notifications@github.com>:

**Comment by UFOMelkor** [comment]
> Not sure if it is possible to replace a service in the symfony container with a decorated version of that service.

Should be [no problem](http://symfony.com/doc/current/service_container/service_decoration.html).

Another point for the v7 roadmap: Lets finally add documentation for the bundle.

**Comment by mablae** [comment]
@codeliner Thank you! The related WIP PR is here: #4

**Comment by mablae** [comment]
> v7:
>moved to event-sourcing package

>Configuration may need to be updated to point to other namespaces, but other than that I don't think that we need a lot of changes here.

@codeliner Should `event-store-symfony-bundle` rely on `event-sourcing` or is EventSourcing optional?

**Comment by UFOMelkor** [comment]
@mablae @codeliner Can this be closed?

**Comment by codeliner** [comment]
#4 is merged so I'd say yes
