### ISSUE TITLE
projection:names command should work without projection name argument

### ISSUE THREAD

**Issue by codeliner** [prooph/event-store-symfony-bundle#21]
Tried a short fix: https://github.com/prooph/event-store-symfony-bundle/pull/20
But this breaks the command entirely, so we need to find a better way.

**Comment by camuthig** [comment]
Should the command be displaying the projections for all managers or should it take a `manager` argument with the name of the manager? I can see benefits to both ways.

**Comment by codeliner** [comment]
Good idea/question

What about: by default for all managers with an option to filter by manager name?

**Comment by camuthig** [comment]
That works for me. I've got something in the works right now. Need to get the offset right and then I will submit a PR.
