### ISSUE TITLE
Command event-store:projection:names broken

### ISSUE THREAD

**Issue by hvanoch** [prooph/event-store-symfony-bundle#25]
The symfony command event-store:projection:names is broken.
it now returns 

>  [Symfony\Component\Console\Exception\InvalidArgumentException]  
>   The "projection-name" argument does not exist.             

It is because it extends the AbstractProjectionCommand which tries to get the projection name of the argument. But that is not used in that command.

**Comment by codeliner** [comment]
@hvanoch Can you retry with latest master? Merged the fix 5h ago ;)
https://github.com/prooph/event-store-symfony-bundle/pull/24

**Comment by hvanoch** [comment]
Perfect! Thanks.

**Comment by codeliner** [comment]
great!
