### ISSUE TITLE
Raise version of symfony dependencies

### ISSUE THREAD

**Issue by UFOMelkor** [prooph/event-store-symfony-bundle#30]
Currently the bundle requires the symfony dependencies in version `~2.8 || ~3.0`.
Within the DI-Extension the `Symfony\Component\DependencyInjection\DefinitionDecorator` is used which is deprecated since v3.3 and will be removed in v4.0.

Because the service-bus-symfony-bundle already requires at least v3.3, I would suggest to raise the version of the symfony dependencies to `~3.3` and get rid of the `DefinitionDecorator`.

See prooph/service-bus-symfony-bundle#32

**Comment by enumag** [comment]
Any news? This bundle is the last dependency blocking me from Symfony 4.

**Comment by UFOMelkor** [comment]
service-bus-symfony-bundle is almost ready for a stable release, so I hope to have more time for the event-store-symfony-bundle next weeks.

First thing I plan to start with are tests. Once they are done, Symfony 4 / PHP 7.2 might be the next to address. As always every help is appreciated 😉

**Comment by enumag** [comment]
I could help with the upgrade but without existing tests it would not be safe. I do not know enough about prooph to write the tests myself. Let me know when the tests are done, I'll see what I can do about Symfony 4.
