### ISSUE TITLE
Deprecated relying on its factory's return-type to define the class of service

### ISSUE THREAD

**Issue by mkurzeja** [prooph/event-store-symfony-bundle#37]
In some environments I get the following error:

```Relying on its factory's return-type to define the class of service "prooph_event_store.projection_manager.xxx_projection_manager" is deprecated since Symfony 3.3 and won't work in 4.0. Set the "class" attribute to "Prooph\EventStore\Projection\ProjectionManager" on the service definition instead: 1x```

I assume the best solution is to add the class parameter when creating the service inside  `\Prooph\Bundle\EventStore\DependencyInjection\ProophEventStoreExtension::loadProjectionManagers`

**Comment by mkurzeja** [comment]
In some environments: each time when I run phpunit on my test suite and Symfony is building the dependency injection container - I get this error. Whats worse, phpunit is returning != 0 exit code. 

I'm currently warming up the cache before running tests, but it would be great to fix this issue.

**Comment by codeliner** [comment]
Solved by #38
