### ISSUE TITLE
ProjectionManagerFactory doesn't handle EventStoreDecorator

### ISSUE THREAD

**Issue by camilledejoye** [prooph/event-store-symfony-bundle#55]
Hi there,

First of all, thanks for the work done!

It appears that the ProjectionManagerFactory hard code the types of allowed EventStore.
My problem was that I'm using a TransactionalActionEventEmitterEventStore, to be specific :)

So when I tried to configure a projection manager to use this store, if failed.
Indeed this store doesn't implement any of the providing PDO implementation of the event store.

You ask to open an issue before make any PR, so here I am.

The PR is ready anyway, I will push it to my fork onto a new branch with this issue number.

There is the link to the [proposed solution](https://github.com/elythyr/event-store-symfony-bundle/commit/595ba7fe225dfe07d488926ef4e8e74e78d1157b)

**Comment by codeliner** [comment]
@elythyr thx! The proposed solution looks good! PR would be great
