### ISSUE TITLE
Cannot autowire service when installing the bundle

### ISSUE THREAD

**Issue by DavidGarciaCat** [prooph/event-store-symfony-bundle#61]
Hey there,

When I try to install the vendor through Composer to my Symfony 4.2 project:

```bash
composer require prooph/event-store-symfony-bundle
```

Then it throws an error due to the services are not defined through the Namespace\Class (or there aren't aliases for it):

![Screenshot 2019-05-20 at 16 17 43](https://user-images.githubusercontent.com/7809429/58032892-6926e180-7b1b-11e9-9df2-7ecaa26f5592.png)

This looks like a blocker for those users that are trying to use the bundle for the very first time.

Would be good if the services can define a valid Alias if you don't want to replace it everywhere.

Cheers,

**Comment by dimacros** [comment]
I also have the same error

**Comment by unixslayer** [comment]
this problem will not occur anymore due bundle recipe won't install the problematic command anymore starting from `v0.10`
