### ISSUE TITLE
Deprecated callable reference to self in PHP 8.2

### ISSUE THREAD

**Issue by mkilmanas** [prooph/event-store-symfony-bundle#92]
In PHP 8.2 some [formats of callables were deprecated](https://php.watch/versions/8.2/partially-supported-callable-deprecation) - one of those formats is `['self', 'myMethod']` which is exactly what is used here: https://github.com/prooph/event-store-symfony-bundle/blob/34204bb403b94c1a3c098b1cd137fa68edef66a8/src/Projection/Options/ProjectionOptionsFactory.php#L21-L26

This raises a deprecation warning when running this code on PHP 8.2:
```
Deprecated: Use of "self" in callables is deprecated
```

**Comment by unixslayer** [comment]
@mkilmanas solved in #94
