### ISSUE TITLE
Symfony 7 support

### ISSUE THREAD

**Issue by monchyrcg** [prooph/event-store-symfony-bundle#93]
Hi, I would like to know if in your roadmap is the upgrade to symfony 7.

Thanks,

**Comment by Mattin** [comment]
This bundle is dead for 2 years so I doubt there will be any upgrade in future.

**Comment by unixslayer** [comment]
@monchyrcg Symfony 7 support is added in #94 

@Mattin bundle is not dead but lack of support on daily basis. Nevertheless it is open for contribusion.
